// test-case/jogak-react-shop/src/pages/CartPage.tsx
import type { ReactElement } from 'react'
import { useNavigate } from 'react-router-dom'
import { products } from '@jogak-shop/shared'
import { CartItemRow } from '../components/molecules/CartItemRow.tsx'
import { CartSummary } from '../components/organisms/CartSummary.tsx'
import { Button } from '../components/atoms/Button.tsx'
import { cartStore, useCart } from '../lib/cart-store.ts'

export function CartPage(): ReactElement {
  const cart = useCart()
  const navigate = useNavigate()
  const empty = cart.lines.length === 0

  return (
    <div className="grid grid-cols-12 gap-6">
      <div className="col-span-12 lg:col-span-8 space-y-3">
        <header className="flex items-center justify-between">
          <h1 className="text-2xl font-bold text-ink-900">장바구니</h1>
          {!empty ? (
            <button
              type="button"
              onClick={() => cartStore.clear()}
              className="text-sm text-ink-400 hover:text-danger-500"
            >
              전체 비우기
            </button>
          ) : null}
        </header>
        {empty ? (
          <div className="text-center py-16 space-y-4 bg-white border border-dashed border-ink-200 rounded-lg">
            <p className="text-ink-400">장바구니가 비어 있습니다.</p>
            <Button onClick={() => navigate('/')} variant="secondary">쇼핑 계속하기</Button>
          </div>
        ) : (
          <div className="space-y-3">
            {cart.lines.map((line) => {
              const product = products.find((p) => p.id === line.productId)
              if (!product) return null
              return (
                <CartItemRow
                  key={`${line.productId}:${line.variantId ?? '_'}`}
                  line={line}
                  product={product}
                  onQuantityChange={cartStore.setQuantity}
                  onRemove={cartStore.remove}
                />
              )
            })}
          </div>
        )}
      </div>
      <div className="col-span-12 lg:col-span-4">
        <CartSummary cart={cart} onCheckout={() => navigate('/checkout')} />
      </div>
    </div>
  )
}

// test-case/jogak-svelte-shop/src/pages/CartPage.svelte
<script lang="ts">
  import { navigate } from 'svelte-routing'
  import { products } from '@jogak-shop/shared'
  import CartItemRow from '../components/molecules/CartItemRow.svelte'
  import CartSummary from '../components/organisms/CartSummary.svelte'
  import Button from '../components/atoms/Button.svelte'
  import { cart } from '../lib/cart-store.svelte'

  let empty = $derived(cart.state.lines.length === 0)
</script>

<div class="grid grid-cols-12 gap-6">
  <div class="col-span-12 lg:col-span-8 space-y-3">
    <header class="flex items-center justify-between">
      <h1 class="text-2xl font-bold text-ink-900">장바구니</h1>
      {#if !empty}
        <button type="button" class="text-sm text-ink-400 hover:text-danger-500" onclick={() => cart.clear()}>
          전체 비우기
        </button>
      {/if}
    </header>
    {#if empty}
      <div class="text-center py-16 space-y-4 bg-white border border-dashed border-ink-200 rounded-lg">
        <p class="text-ink-400">장바구니가 비어 있습니다.</p>
        <Button label="쇼핑 계속하기" variant="secondary" onclick={() => navigate('/')} />
      </div>
    {:else}
      <div class="space-y-3">
        {#each cart.state.lines as line (`${line.productId}:${line.variantId ?? '_'}`)}
          {@const product = products.find((p) => p.id === line.productId)}
          {#if product}
            <CartItemRow
              {line}
              {product}
              onquantitychange={cart.setQuantity}
              onremove={cart.remove}
            />
          {/if}
        {/each}
      </div>
    {/if}
  </div>
  <div class="col-span-12 lg:col-span-4">
    <CartSummary cart={cart.state} oncheckout={() => navigate('/checkout')} />
  </div>
</div>
