// test-case/jogak-svelte-shop/src/components/organisms/ProductGrid.showcase.svelte
<script lang="ts">
  import { products } from '@jogak-shop/shared'
  import ProductGrid from './ProductGrid.svelte'

  let {
    kind = 'all' as 'all' | 'apparel' | 'tech' | 'beauty' | 'sports' | 'empty',
    columns = 4 as 2 | 3 | 4,
    emptyMessage = '상품이 없습니다.',
  }: {
    kind?: 'all' | 'apparel' | 'tech' | 'beauty' | 'sports' | 'empty'
    columns?: 2 | 3 | 4
    emptyMessage?: string
  } = $props()

  let filtered = $derived(
    kind === 'all'
      ? products
      : kind === 'empty'
        ? []
        : products.filter((p) => p.category === kind),
  )
</script>

<ProductGrid products={filtered} {columns} {emptyMessage} />

// test-case/jogak-vue-shop/src/components/organisms/ProductGrid.showcase.vue
<script setup lang="ts">
import { computed } from 'vue'
import { products } from '@jogak-shop/shared'
import ProductGrid from './ProductGrid.vue'

const props = withDefaults(
  defineProps<{
    kind?: 'all' | 'apparel' | 'tech' | 'beauty' | 'sports' | 'empty'
    columns?: 2 | 3 | 4
    emptyMessage?: string
  }>(),
  { kind: 'all', columns: 4, emptyMessage: '상품이 없습니다.' },
)

const filtered = computed(() =>
  props.kind === 'all'
    ? products
    : props.kind === 'empty'
      ? []
      : products.filter((p) => p.category === props.kind),
)
</script>

<template>
  <ProductGrid :products="filtered" :columns="columns" :empty-message="emptyMessage" />
</template>
