// examples/vue/src/components/Counter.vue
<script setup lang="ts">
import { ref } from 'vue'

const props = withDefaults(
  defineProps<{
    /** 초기값 */
    initial?: number
    /** 증감 단위 */
    step?: number
    /** 라벨 */
    label?: string
  }>(),
  { initial: 0, step: 1, label: 'count' },
)

const value = ref(props.initial)
</script>

<template>
  <div
    :style="{
      display: 'inline-flex',
      alignItems: 'center',
      gap: '8px',
      padding: '8px',
      border: '1px solid #e5e7eb',
      borderRadius: '6px',
      fontFamily: 'system-ui, sans-serif',
    }"
    data-testid="vue-counter"
  >
    <button
      type="button"
      @click="value -= step"
      :style="{
        height: '32px',
        width: '32px',
        background: '#f1f5f9',
        border: 'none',
        borderRadius: '4px',
        cursor: 'pointer',
      }"
      aria-label="decrement"
    >
      −
    </button>
    <span :style="{ minWidth: '64px', textAlign: 'center', fontSize: '14px' }">
      {{ label }}: <strong>{{ value }}</strong>
    </span>
    <button
      type="button"
      @click="value += step"
      :style="{
        height: '32px',
        width: '32px',
        background: '#0f172a',
        color: '#fff',
        border: 'none',
        borderRadius: '4px',
        cursor: 'pointer',
      }"
      aria-label="increment"
    >
      +
    </button>
  </div>
</template>

// examples/react-vite/src/components/ui/Counter.tsx
import { useState } from 'react'

export interface CounterProps {
  /** 초기값 */
  readonly initial?: number
  /** 증감 단위 */
  readonly step?: number
  /** 라벨 */
  readonly label?: string
}

export function Counter({ initial = 0, step = 1, label = 'count' }: CounterProps) {
  const [value, setValue] = useState(initial)
  return (
    <div className="inline-flex items-center gap-2 rounded-md border border-border bg-background p-2">
      <button
        type="button"
        onClick={() => setValue((v) => v - step)}
        className="h-8 w-8 rounded-md bg-secondary text-secondary-foreground"
        aria-label="decrement"
      >
        −
      </button>
      <span className="min-w-16 text-center text-sm">
        {label}: <strong>{value}</strong>
      </span>
      <button
        type="button"
        onClick={() => setValue((v) => v + step)}
        className="h-8 w-8 rounded-md bg-primary text-primary-foreground"
        aria-label="increment"
      >
        +
      </button>
    </div>
  )
}
