// packages/ui/src/examples/Button/Button.tsx
import type { ReactElement, MouseEvent } from 'react'

export type ButtonVariant = 'primary' | 'secondary' | 'danger'

export interface ButtonProps {
  readonly label: string
  readonly variant?: ButtonVariant
  readonly disabled?: boolean
  readonly onClick?: (e: MouseEvent<HTMLButtonElement>) => void
}

const styles: Record<ButtonVariant, React.CSSProperties> = {
  primary: { background: '#2563eb', color: '#fff', border: 'none' },
  secondary: { background: '#fff', color: '#374151', border: '1px solid #d1d5db' },
  danger: { background: '#dc2626', color: '#fff', border: 'none' },
}

export function Button({ label, variant = 'primary', disabled = false, onClick }: ButtonProps): ReactElement {
  return (
    <button
      type="button"
      disabled={disabled}
      onClick={onClick}
      style={{
        ...styles[variant],
        padding: '8px 16px',
        borderRadius: 6,
        fontSize: 14,
        fontWeight: 500,
        cursor: disabled ? 'not-allowed' : 'pointer',
        opacity: disabled ? 0.5 : 1,
      }}
    >
      {label}
    </button>
  )
}

// examples/vue/src/components/Button.vue
<script setup lang="ts">
type ButtonVariant = 'primary' | 'secondary' | 'destructive'
type ButtonSize = 'sm' | 'md' | 'lg'

const props = withDefaults(
  defineProps<{
    /** 버튼 라벨 */
    label?: string
    /** 시각적 변형 */
    variant?: ButtonVariant
    /** 크기 */
    size?: ButtonSize
    /** 비활성화 */
    disabled?: boolean
  }>(),
  {
    label: 'Button',
    variant: 'primary',
    size: 'md',
    disabled: false,
  },
)

const sizeStyle: Record<ButtonSize, { padding: string; fontSize: string; height: string }> = {
  sm: { padding: '0 12px', fontSize: '12px', height: '32px' },
  md: { padding: '0 16px', fontSize: '14px', height: '36px' },
  lg: { padding: '0 24px', fontSize: '16px', height: '44px' },
}

const variantStyle: Record<ButtonVariant, { background: string; color: string; border: string }> = {
  primary: { background: '#0f172a', color: '#fff', border: 'none' },
  secondary: { background: '#f1f5f9', color: '#0f172a', border: 'none' },
  destructive: { background: '#dc2626', color: '#fff', border: 'none' },
}
</script>

<template>
  <button
    :disabled="disabled"
    :style="{
      ...sizeStyle[size],
      ...variantStyle[variant],
      borderRadius: '6px',
      fontWeight: 500,
      cursor: disabled ? 'not-allowed' : 'pointer',
      opacity: disabled ? 0.5 : 1,
      fontFamily: 'system-ui, sans-serif',
    }"
    data-testid="vue-button"
  >
    {{ label }}
  </button>
</template>
