// benchmarks/baselines/shared/components/Card.tsx
import * as React from 'react'

export interface CardProps {
  /** 카드 제목 */
  readonly title: string
  /** 카드 설명 */
  readonly description?: string
  /** 푸터 영역 */
  readonly footer?: React.ReactNode
  /** 강조 톤 */
  readonly tone?: 'neutral' | 'primary' | 'warning'
}

const TONE_STYLE: Record<NonNullable<CardProps['tone']>, React.CSSProperties> = {
  neutral: { borderColor: '#e2e8f0', background: '#fff' },
  primary: { borderColor: '#3b82f6', background: '#eff6ff' },
  warning: { borderColor: '#f59e0b', background: '#fffbeb' },
}

export function Card(props: CardProps): React.JSX.Element {
  const { title, description, footer, tone = 'neutral' } = props
  return (
    <div
      style={{
        ...TONE_STYLE[tone],
        border: '1px solid',
        borderRadius: 8,
        padding: 16,
        maxWidth: 360,
        boxShadow: '0 1px 2px rgba(15, 23, 42, 0.04)',
      }}
    >
      <h3 style={{ margin: 0, fontSize: 16, fontWeight: 600 }}>{title}</h3>
      {description !== undefined && (
        <p style={{ margin: '8px 0 0', fontSize: 13, color: '#475569' }}>{description}</p>
      )}
      {footer !== undefined && (
        <div style={{ marginTop: 12, paddingTop: 12, borderTop: '1px solid #e2e8f0' }}>{footer}</div>
      )}
    </div>
  )
}

// examples/vue/src/components/Card.vue
<script setup lang="ts">
withDefaults(
  defineProps<{
    /** 제목 */
    title?: string
    /** 설명 */
    description?: string
  }>(),
  { title: 'Card', description: '' },
)
</script>

<template>
  <div
    :style="{
      width: '320px',
      padding: '24px',
      borderRadius: '8px',
      border: '1px solid #e5e7eb',
      boxShadow: '0 1px 2px rgba(0,0,0,0.05)',
      fontFamily: 'system-ui, sans-serif',
      background: '#fff',
    }"
    data-testid="vue-card"
  >
    <h3 :style="{ margin: '0 0 4px', fontSize: '16px', fontWeight: 600 }">{{ title }}</h3>
    <p v-if="description" :style="{ margin: 0, fontSize: '14px', color: '#6b7280' }">
      {{ description }}
    </p>
  </div>
</template>
