// examples/svelte/src/components/Card.svelte
<script lang="ts">
  let {
    title = 'Card',
    description = '',
  }: { title?: string; description?: string } = $props()
</script>

<div
  style="width: 320px; padding: 24px; border-radius: 8px; border: 1px solid #e5e7eb; box-shadow: 0 1px 2px rgba(0,0,0,0.05); font-family: system-ui, sans-serif; background: #fff;"
  data-testid="svelte-card"
>
  <h3 style="margin: 0 0 4px; font-size: 16px; font-weight: 600;">{title}</h3>
  {#if description}
    <p style="margin: 0; font-size: 14px; color: #6b7280;">{description}</p>
  {/if}
</div>

// examples/vue/src/components/Card.vue
<script setup lang="ts">
withDefaults(
  defineProps<{
    /** 제목 */
    title?: string
    /** 설명 */
    description?: string
  }>(),
  { title: 'Card', description: '' },
)
</script>

<template>
  <div
    :style="{
      width: '320px',
      padding: '24px',
      borderRadius: '8px',
      border: '1px solid #e5e7eb',
      boxShadow: '0 1px 2px rgba(0,0,0,0.05)',
      fontFamily: 'system-ui, sans-serif',
      background: '#fff',
    }"
    data-testid="vue-card"
  >
    <h3 :style="{ margin: '0 0 4px', fontSize: '16px', fontWeight: 600 }">{{ title }}</h3>
    <p v-if="description" :style="{ margin: 0, fontSize: '14px', color: '#6b7280' }">
      {{ description }}
    </p>
  </div>
</template>
