// test-case/jogak-vue-shop/src/components/molecules/ReviewItem.showcase.vue
<script setup lang="ts">
import { computed } from 'vue'
import { reviews } from '@jogak-shop/shared'
import ReviewItem from './ReviewItem.vue'

const props = withDefaults(
  defineProps<{ reviewId?: string; compact?: boolean }>(),
  { reviewId: 'r-001', compact: false },
)
const review = computed(() => reviews.find((r) => r.id === props.reviewId) ?? reviews[0])
</script>

<template>
  <div class="max-w-2xl">
    <ReviewItem v-if="review" :review="review" :compact="compact" />
  </div>
</template>

// test-case/jogak-svelte-shop/src/components/molecules/ReviewItem.showcase.svelte
<script lang="ts">
  import { reviews } from '@jogak-shop/shared'
  import ReviewItem from './ReviewItem.svelte'

  let {
    reviewId = 'r-001',
    compact = false,
  }: { reviewId?: string; compact?: boolean } = $props()

  let review = $derived(reviews.find((r) => r.id === reviewId) ?? reviews[0])
</script>

<div class="max-w-2xl">
  {#if review}<ReviewItem {review} {compact} />{/if}
</div>
