// test-case/jogak-svelte-shop/src/components/molecules/CartItemRow.showcase.svelte
<script lang="ts">
  import { products } from '@jogak-shop/shared'
  import CartItemRow from './CartItemRow.svelte'

  let {
    productId = 'p-001',
    initial = 1,
  }: { productId?: string; initial?: number } = $props()

  let qty = $state(initial)
  let removed = $state(false)
  let product = $derived(products.find((p) => p.id === productId) ?? products[0])
  let variantId = $derived(product?.variants[0]?.id ?? null)
  let line = $derived({ productId: product!.id, variantId, quantity: qty })
</script>

{#if removed}
  <p class="text-sm text-ink-400 p-4">(삭제됨)</p>
{:else if product}
  <div class="max-w-2xl">
    <CartItemRow
      {line}
      {product}
      onquantitychange={(_, __, n) => (qty = n)}
      onremove={() => (removed = true)}
    />
  </div>
{/if}

// test-case/jogak-vue-shop/src/components/molecules/CartItemRow.showcase.vue
<script setup lang="ts">
import { computed, ref } from 'vue'
import { products } from '@jogak-shop/shared'
import CartItemRow from './CartItemRow.vue'

const props = withDefaults(
  defineProps<{ productId?: string; initial?: number }>(),
  { productId: 'p-001', initial: 1 },
)
const qty = ref(props.initial)
const removed = ref(false)
const product = computed(() => products.find((p) => p.id === props.productId) ?? products[0])
const variantId = computed(() => product.value?.variants[0]?.id ?? null)
const line = computed(() => ({ productId: product.value!.id, variantId: variantId.value, quantity: qty.value }))
</script>

<template>
  <p v-if="removed" class="text-sm text-ink-400 p-4">(삭제됨)</p>
  <div v-else class="max-w-2xl">
    <CartItemRow
      v-if="product"
      :line="line"
      :product="product"
      @quantity-change="(_, __, n) => qty = n"
      @remove="removed = true"
    />
  </div>
</template>
