// test-case/jogak-svelte-shop/src/components/molecules/ProductCard.showcase.svelte
<script lang="ts">
  import { products } from '@jogak-shop/shared'
  import ProductCard from './ProductCard.svelte'

  let {
    productId = 'p-001',
    layout = 'grid' as 'grid' | 'horizontal',
  }: { productId?: string; layout?: 'grid' | 'horizontal' } = $props()

  let product = $derived(products.find((p) => p.id === productId) ?? products[0])
</script>

<div class={layout === 'horizontal' ? 'max-w-md' : 'max-w-xs'}>
  {#if product}<ProductCard {product} {layout} />{/if}
</div>

// test-case/jogak-vue-shop/src/components/molecules/ProductCard.showcase.vue
<script setup lang="ts">
import { computed } from 'vue'
import { products } from '@jogak-shop/shared'
import ProductCard from './ProductCard.vue'

const props = withDefaults(
  defineProps<{ productId?: string; layout?: 'grid' | 'horizontal' }>(),
  { productId: 'p-001', layout: 'grid' },
)
const product = computed(() => products.find((p) => p.id === props.productId) ?? products[0])
</script>

<template>
  <div :class="layout === 'horizontal' ? 'max-w-md' : 'max-w-xs'">
    <ProductCard v-if="product" :product="product" :layout="layout" />
  </div>
</template>
