// test-case/jogak-react-shop/src/App.tsx
import type { ReactElement } from 'react'
import { BrowserRouter, Route, Routes } from 'react-router-dom'
import { ShopLayout } from './components/layouts/ShopLayout.tsx'
import { ProductsPage } from './pages/ProductsPage.tsx'
import { ProductDetailPage } from './pages/ProductDetailPage.tsx'
import { CartPage } from './pages/CartPage.tsx'
import { CheckoutPage } from './pages/CheckoutPage.tsx'
import { AccountPage } from './pages/AccountPage.tsx'

export function App(): ReactElement {
  return (
    <BrowserRouter>
      <Routes>
        <Route element={<ShopLayout />}>
          <Route path="/" element={<ProductsPage />} />
          <Route path="/category/:slug" element={<ProductsPage />} />
          <Route path="/product/:slug" element={<ProductDetailPage />} />
          <Route path="/cart" element={<CartPage />} />
          <Route path="/checkout" element={<CheckoutPage />} />
          <Route path="/account" element={<AccountPage />} />
        </Route>
      </Routes>
    </BrowserRouter>
  )
}

// test-case/jogak-svelte-shop/src/App.svelte
<script lang="ts">
  import { Router, Route } from 'svelte-routing'
  import ShopLayout from './components/layouts/ShopLayout.svelte'
  import ProductsPage from './pages/ProductsPage.svelte'
  import ProductDetailPage from './pages/ProductDetailPage.svelte'
  import CartPage from './pages/CartPage.svelte'
  import CheckoutPage from './pages/CheckoutPage.svelte'
  import AccountPage from './pages/AccountPage.svelte'
</script>

<Router>
  <ShopLayout>
    {#snippet children()}
      <Route path="/"><ProductsPage /></Route>
      <Route path="/category/:slug" let:params>
        <ProductsPage slug={params.slug ?? ''} />
      </Route>
      <Route path="/product/:slug" let:params>
        <ProductDetailPage slug={params.slug ?? ''} />
      </Route>
      <Route path="/cart"><CartPage /></Route>
      <Route path="/checkout"><CheckoutPage /></Route>
      <Route path="/account"><AccountPage /></Route>
    {/snippet}
  </ShopLayout>
</Router>
